# Generated by Django 2.2 on 2019-10-23 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KNGarment_Order_TrackPro_App', '0004_washing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finishing',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='KNGarment_Order_TrackPro_App.Process')),
                ('finishing_rate', models.IntegerField()),
                ('finishing_delivery_quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Finishing Order',
                'verbose_name_plural': 'Finishing Orders List',
            },
            bases=('KNGarment_Order_TrackPro_App.process',),
        ),
    ]
