# Generated by Django 2.2 on 2019-10-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KNGarment_Order_TrackPro_App', '0005_finishing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_order_remark',
            field=models.CharField(blank=True, max_length=920),
        ),
    ]
